export { default as Contacts } from './Contacts/Contacts'
export { default as ContactDetail } from './Contacts/ContactDetail'
export { default as Login } from './Login/Login'
export { default as Callcenter } from './Callcenter/Callcenter'
export { default as Dialpad } from './Call/Dialpad'
export { default as Startup } from './Startup/Startup'
